from typing import Any

from ._actions import ActionFinder

def readSnapshot(filename: str, /) -> Any: ...
def writeSnapshot(filename: str, particles: Any, format: str = "t") -> None: ...
def setUnits(**kwargs: Any) -> None: ...
def getUnits() -> dict[str, float]: ...
def setRandomSeed(seed: int) -> None: ...
def sampleNdim(fnc: Any, nsamples: int, **kwargs: Any) -> Any: ...
def integrateNdim(fnc: Any, nsamples: int, **kwargs: Any) -> Any: ...
def orbit(**kwargs: Any) -> Any: ...
def splineApprox(knots: Any, x: Any, y: Any, **kwargs: Any) -> Any: ...
def splineLogDensity(knots: Any, x: Any, **kwargs: Any) -> Any: ...
def solveOpt(**kwargs: Any) -> Any: ...
def ghMoments(
    degree: int, gridv: Any, matrix: Any, ghorder: int, **kwargs: Any
) -> Any: ...

class setNumThreads:
    def __init__(self, num_threads: int) -> None: ...
    def __enter__(self) -> setNumThreads: ...
    def __exit__(self, *args: Any) -> None: ...

actions: ActionFinder
