from array import array
from collections.abc import Generator, Iterable, Sequence
from os import PathLike
from types import TracebackType
from typing import BinaryIO, ClassVar, Literal, Protocol, Self, SupportsIndex, overload

import numpy as np
from numpy.typing import ArrayLike, DTypeLike
from optype import numpy as onp

__all__: list[str] = ["NemoFile"]

type _Filename = str | bytes | PathLike[str] | PathLike[bytes] | int
type _Mode = Literal["r", "x", "w", "a"]
type _IntegerCode = Literal["b", "B", "h", "H", "i", "I", "l", "L", "q", "Q"]
type _FloatCode = Literal["f", "d"]
type _Numeric = (
    np.int8 | np.int16 | np.int32 | np.int64 | np.float16 | np.float32 | np.float64
)
type _Data = onp.ArrayND[_Numeric | np.bytes_] | str | _Items | None
type _Snapshot = dict[str, _Data | _Numeric | np.bytes_]

class _Items(Protocol):
    def __getitem__(self, key: str) -> list[_Item]: ...
    def __contains__(self, key: object) -> bool: ...
    def __len__(self) -> int: ...
    def keys(self) -> list[str]: ...
    def values(self) -> Generator[_Item]: ...

class _Item(Protocol):
    tagstring: str
    dimensions: Sequence[int]
    mustswap: bool
    data: _Data
    typecharacter: ClassVar[str]
    def is_plural(self) -> bool: ...
    def read(self, nemofile: NemoFile) -> None: ...
    def write(self, nemofile: NemoFile) -> None: ...
    def isEndOfSet(self) -> bool: ...
    def isEndOfHistory(self) -> bool: ...

class NemoFile:
    file: BinaryIO
    filename: _Filename
    SingMagic: ClassVar[int] = 0x0992
    PlurMagic: ClassVar[int] = 0x0B92
    reversed_SingMagic: ClassVar[int] = 0x9209
    reversed_PlurMagic: ClassVar[int] = 0x920B
    def __init__(self, filename: _Filename, mode: _Mode = "r") -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def close(self) -> None: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> _Snapshot: ...
    def next(self) -> _Snapshot: ...
    def read(self) -> _Snapshot | None: ...
    def write[Value: ArrayLike](self, snapshot: dict[str, Value]) -> None: ...
    def read_magic_number(self) -> int | None: ...
    @overload
    def read_array(self, typetag: _IntegerCode) -> array[int]: ...
    @overload
    def read_array(self, typetag: _FloatCode) -> array[float]: ...
    @overload
    def read_array(self, typetag: Literal["u", "w"]) -> array[str]: ...
    def read_string(self) -> str: ...
    def read_fixed_array[Scalar: np.generic](
        self, datatype: np.dtype[Scalar], count: int | np.integer
    ) -> onp.Array1D[Scalar]: ...
    def get_item_header(
        self,
    ) -> tuple[str, str, list[int], bool] | tuple[None, None, None, None]: ...
    def read_item(self) -> _Item | None: ...
    def write_magic_number(self, is_plural: bool) -> None: ...
    @overload
    def write_array(
        self, typetag: _IntegerCode, data: Iterable[SupportsIndex] | bytes | bytearray
    ) -> None: ...
    @overload
    def write_array(
        self, typetag: _FloatCode, data: Iterable[float] | bytes | bytearray
    ) -> None: ...
    @overload
    def write_array(
        self, typetag: Literal["u", "w"], data: str | Iterable[str] | bytes | bytearray
    ) -> None: ...
    def write_string(self, string: str) -> None: ...
    def write_item_header(self, item: _Item) -> None: ...
    def write_item(self, item: _Item) -> None: ...
    def write_fixed_array(self, data: ArrayLike, datatype: DTypeLike) -> None: ...

def open(filename: _Filename, mode: _Mode = "r") -> NemoFile: ...
