from typing import overload

import numpy as np
from optype import numpy as onp

class Orbit:
    def __new__(cls) -> Orbit: ...
    @overload
    def __call__(self, time: onp.ToFloat, /) -> onp.Array1D[np.float64]: ...
    @overload
    def __call__(self, time: onp.ToFloat1D, /) -> onp.Array2D[np.float64]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> float: ...
