import array
from collections.abc import Callable, Iterable, Iterator, Sequence
from os import PathLike
from types import TracebackType
from typing import Any, ClassVar, Final, Literal, Self, overload, override

import numpy as np
from numpy import typing as npt
from optype import numpy as onp

__all__: list[str] = ["NemoFile"]

type _IntTypeTag = Literal["b", "B", "h", "H", "i", "I", "l", "L", "q", "Q"]
type _FloatTypeTag = Literal["f", "d"]
type _StrTypeTag = Literal["u"]
type _TypeTag = _IntTypeTag | _FloatTypeTag | _StrTypeTag
type _NemoTypeCharacter = Literal[
    "a",  # AnyItem
    "c",  # CharItem
    "b",  # ByteItem
    "s",  # ShortItem
    "i",  # IntItem
    "l",  # LongItem
    "h",  # HalfpItem
    "f",  # FloatItem
    "d",  # DoubleItem
    "(",  # SetItem
    ")",  # TesItem
    "[",  # StoryItem
    "]",  # YrotsItem
]
# NOTE: `data` changes type a lot and there isn't too much that is in common with the types.
type _NemoItemData = Any
type _SnapshotValue = np.generic | npt.NDArray[np.generic]
type _Snapshot = dict[str, _SnapshotValue]

# NOTE: The metaclass must be a subclass of type and there is no restriction on the generic
def add_metaclass[T](metaclass: type[type[Any]]) -> Callable[[type[T]], type[T]]: ...

class NemoItemType(type):
    mapping: ClassVar[dict[str, type[NemoItem]]]

    def __new__(
        mcls,
        name: str,
        bases: tuple[type, ...],
        # NOTE: Mirrors `type.__new__`'s namespace.
        namespace: dict[str, Any],
        # NOTE: Mirrors `type.__new__`'s kwargs.
        **kwargs: Any,
    ) -> NemoItemType: ...
    @classmethod
    def new_item(
        cls,
        typecharacter: str,
        tagstring: str,
        dimensions: list[int],
        mustswap: bool = False,
    ) -> NemoItem: ...

class NemoItem(metaclass=NemoItemType):
    typecharacter: ClassVar[_NemoTypeCharacter]
    datatype: ClassVar[npt.DTypeLike | None]

    tagstring: str
    dimensions: list[int]
    mustswap: bool
    data: _NemoItemData

    def __init__(
        self,
        tagstring: str,
        dimensions: list[int] = [1],
        data: _NemoItemData | None = None,
        mustswap: bool = False,
    ) -> None: ...
    def is_plural(self) -> bool: ...
    def read(self, nemofile: NemoFile) -> None: ...
    def write(self, nemofile: NemoFile) -> None: ...
    def postprocess(self) -> None: ...
    def preprocess(self) -> _NemoItemData: ...
    def isEndOfSet(self) -> bool: ...
    def isEndOfHistory(self) -> bool: ...

class CharItem(NemoItem):
    @override
    def preprocess(self) -> onp.Array1D[np.bytes_]: ...

class AnyItem(NemoItem): ...
class ByteItem(NemoItem): ...
class ShortItem(NemoItem): ...
class IntItem(NemoItem): ...
class LongItem(NemoItem): ...
class HalfpItem(NemoItem): ...
class FloatItem(NemoItem): ...
class DoubleItem(NemoItem): ...
class SetItem(NemoItem): ...
class TesItem(NemoItem): ...
class StoryItem(NemoItem): ...
class YrotsItem(NemoItem): ...

class NemoFile:
    def __init__(
        self, filename: PathLike[str], mode: Literal["r", "x", "w", "a"] = "r"
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None: ...
    def close(self) -> None: ...
    def __iter__(self) -> Iterator[NemoFile]: ...

    SingMagic: Final[int] = 0x0992
    PlurMagic: Final[int] = 0x0B92
    reversed_SingMagic: Final[int] = 0x9209
    reversed_PlurMagic: Final[int] = 0x920B

    def read_magic_number(self) -> int | None: ...
    @overload
    def read_array(self, typetag: _IntTypeTag) -> array.array[int]: ...
    @overload
    def read_array(self, typetag: _FloatTypeTag) -> array.array[float]: ...
    @overload
    def read_array(self, typetag: _StrTypeTag) -> array.array[str]: ...
    def read_string(self) -> str: ...
    def read_fixed_array[T: np.generic](
        self, datatype: np.dtype[T], count: int
    ) -> onp.Array1D[T]: ...
    def get_item_header(
        self,
    ) -> tuple[str, str, Sequence[int], bool] | tuple[None, None, None, None]: ...
    def read_item(self) -> NemoItem: ...
    def write_magic_number(self, is_plural: bool) -> None: ...
    @overload
    def write_array(self, typetag: _IntTypeTag, data: Iterable[int]) -> None: ...
    @overload
    def write_array(self, typetag: _FloatTypeTag, data: Iterable[float]) -> None: ...
    @overload
    def write_array(self, typetag: _StrTypeTag, data: Iterable[str]) -> None: ...
    def write_string(self, string: bytes) -> None: ...
    def write_item_header(self, item: NemoItem) -> None: ...
    def write_item(self, item: NemoItem) -> None: ...
    def write_fixed_array(
        self,
        data: npt.ArrayLike,
        datatype: npt.DTypeLike,
    ) -> None: ...
    def read(self) -> _Snapshot: ...
    def __next__(self) -> _Snapshot: ...
    def write(self, snapshot: _Snapshot) -> None: ...

    next: Callable[[Self], _Snapshot] = __next__
