from collections.abc import Sequence
from typing import Any, Final, overload

import numpy as np
from optype import numpy as onp

__version__: Final[str] = "1.0"
G: Final[float] = 1.0

class Density:
    @overload
    def __init__(self, cumulmass: onp.ToJustFloat64_2D) -> None: ...
    @overload
    def __init__(self, filename: str) -> None: ...
    @overload
    def __init__(self, *args: "Density") -> None: ...
    @overload
    def __init__(
        self,
        *,
        type: str | None = None,
        density: str | None = None,
        mass: float | None = None,
        scaleradius: float | None = None,
        scaleheight: float | None = None,
        p: float | None = None,
        q: float | None = None,
        gamma: float | None = None,
        beta: float | None = None,
        alpha: float | None = None,
        sersicIndex: float | None = None,
        innercutoffradius: float | None = None,
        outercutoffradius: float | None = None,
        cutoffstrength: float | None = None,
        surfacedensity: float | None = None,
        densitynorm: float | None = None,
        w0: float | None = None,
        trunc: float | None = None,
        center: tuple[float, float, float] | str | None = None,
        orientation: tuple[float, float, float] | None = None,
        rotation: float | str | None = None,
        scale: tuple[float, float] | str | None = None,
    ) -> None: ...

    def density(
        self,
        xyz: tuple[float, float, float] | onp.ToJustFloat64_2D,
        t: float | onp.ToJustFloat64_1D | None = None,
    ) -> float | onp.Array1D[np.float64]: ...

    def projectedDensity(self, xyz: float | onp.ToJustFloat64_1D) -> float | onp.Array1D[np.float64]: ...

    def export(self, filename: str) -> None: ...

    def sample(
        self,
        n: int,
        potential: "Potential | None" = None,
        beta: float | None = None,
        kappa: float | None = None,
    ) -> tuple[list[list[float]], list[float]]: ...

    def totalMass(self) -> float: ...
    def enclosedMass(self, r: float | Sequence[float]) -> float | list[float]: ...
    def principalAxes(self, r: float | onp.ToJustFloat64_1D | None = None) -> tuple[list[float], list[float]]: ...
    def name(self) -> str: ...
    def __getitem__(self, index: int) -> "Density | Potential": ...
    def __len__(self) -> int: ...
    def __add__(self, other: "Density") -> "Density": ...

class Potential(Density):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def potential(self, *args: Any, **kwargs: Any) -> Any: ...
    def force(self, *args: Any, **kwargs: Any) -> Any: ...

class ActionFinder:
    def __init__(self, potential: Any, interp: bool = False) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class ActionMapper: ...
class Component: ...
class DistributionFunction: ...
class GalaxyModel: ...
class SelectionFunction: ...
class SelfConsistentModel: ...
class Spline: ...
class Target: ...

def readSnapshot(filename: str, /) -> Any: ...
def writeSnapshot(filename: str, particles: Any, format: str = "t") -> None: ...

def setUnits(**kwargs: Any) -> None: ...
def getUnits() -> dict[str, float]: ...
def setRandomSeed(seed: int) -> None: ...

def sampleNdim(fnc: Any, nsamples: int, **kwargs: Any) -> Any: ...
def integrateNdim(fnc: Any, nsamples: int, **kwargs: Any) -> Any: ...
def orbit(**kwargs: Any) -> Any: ...

def splineApprox(knots: Any, x: Any, y: Any, **kwargs: Any) -> Any: ...
def splineLogDensity(knots: Any, x: Any, **kwargs: Any) -> Any: ...
def solveOpt(**kwargs: Any) -> Any: ...

def ghMoments(degree: int, gridv: Any, matrix: Any, ghorder: int, **kwargs: Any) -> Any: ...

class setNumThreads:
    def __init__(self, num_threads: int) -> None: ...
    def __enter__(self) -> "setNumThreads": ...
    def __exit__(self, *args: Any) -> None: ...

actions: ActionFinder

__all__ = [
    "ActionFinder",
    "ActionMapper",
    "Component",
    "Density",
    "DistributionFunction",
    "G",
    "GalaxyModel",
    "Potential",
    "SelectionFunction",
    "SelfConsistentModel",
    "Spline",
    "Target",
    "__version__",
    "actions",
    "getUnits",
    "ghMoments",
    "integrateNdim",
    "orbit",
    "readSnapshot",
    "sampleNdim",
    "setNumThreads",
    "setRandomSeed",
    "setUnits",
    "solveOpt",
    "splineApprox",
    "splineLogDensity",
    "writeSnapshot",
]
